annotations:
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/certified: rancher # Any application we are adding as a helm chart
  catalog.cattle.io/namespace: cattle-ui-plugin-system # Must prefix with cattle- and suffix with -system=
  catalog.cattle.io/ui-component: plugins # This is added for custom UI deployment of a chart
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/kube-version: '>= 1.16.0-0 < 1.25.0-0'
  catalog.cattle.io/rancher-version: '>= 2.7.0-0 < 2.8.0-0'
apiVersion: v1
appVersion: "1.16.0"
description: A base Plugin Operator Chart for adding plugins to Rancher
name: ui-plugin-operator
type: application
keywords:
- applications
- infrastructure
version: 0.1.0
